//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesEN_UK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesEN_UK() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Core.Resources.ResourcesEN-UK", typeof(ResourcesEN_UK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory copied successfully..
        /// </summary>
        internal static string DirectoryCopied {
            get {
                return ResourceManager.GetString("DirectoryCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Element:.
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ENTER to exit.
        /// </summary>
        internal static string EnterExit {
            get {
                return ResourceManager.GetString("EnterExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters entered.
        /// </summary>
        internal static string ErrorEmptySave {
            get {
                return ResourceManager.GetString("ErrorEmptySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting EasySave....
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File copied successfully..
        /// </summary>
        internal static string FileCopied {
            get {
                return ResourceManager.GetString("FileCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In: .
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid choice.
        /// </summary>
        internal static string InvalidChoice {
            get {
                return ResourceManager.GetString("InvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is running....
        /// </summary>
        internal static string IsRunning {
            get {
                return ResourceManager.GetString("IsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A List:.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-3 =&gt; 1 to 3                                     |.
        /// </summary>
        internal static string ListAnswer1 {
            get {
                return ResourceManager.GetString("ListAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,3 =&gt; 1 and 3                              |.
        /// </summary>
        internal static string ListAnswer2 {
            get {
                return ResourceManager.GetString("ListAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : You have reached the maximum number of saves.
        /// </summary>
        internal static string MaxSaveError {
            get {
                return ResourceManager.GetString("MaxSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | 1 - Plan a save.................................          |.
        /// </summary>
        internal static string Menu1 {
            get {
                return ResourceManager.GetString("Menu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | 2 - Run a save..................................          |.
        /// </summary>
        internal static string Menu2 {
            get {
                return ResourceManager.GetString("Menu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | 3 - Show Logs...................................          |.
        /// </summary>
        internal static string Menu3 {
            get {
                return ResourceManager.GetString("Menu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | 4 - Show state file.............................          |.
        /// </summary>
        internal static string Menu4 {
            get {
                return ResourceManager.GetString("Menu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | 5 - Show schedule...............................          |.
        /// </summary>
        internal static string Menu5 {
            get {
                return ResourceManager.GetString("Menu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 - Quit.........................................
        /// </summary>
        internal static string Menu6 {
            get {
                return ResourceManager.GetString("Menu6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to            1- .
        /// </summary>
        internal static string Number1 {
            get {
                return ResourceManager.GetString("Number1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           2- .
        /// </summary>
        internal static string Number2 {
            get {
                return ResourceManager.GetString("Number2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           3- .
        /// </summary>
        internal static string Number3 {
            get {
                return ResourceManager.GetString("Number3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to            4- .
        /// </summary>
        internal static string Number4 {
            get {
                return ResourceManager.GetString("Number4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             5- .
        /// </summary>
        internal static string Number5 {
            get {
                return ResourceManager.GetString("Number5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out: .
        /// </summary>
        internal static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan a save.
        /// </summary>
        internal static string PlanSave {
            get {
                return ResourceManager.GetString("PlanSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |               What do you want to execute?               |.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a save.
        /// </summary>
        internal static string RunSave {
            get {
                return ResourceManager.GetString("RunSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save date ?                  |.
        /// </summary>
        internal static string SaveDate {
            get {
                return ResourceManager.GetString("SaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save name ?                   |.
        /// </summary>
        internal static string SaveName {
            get {
                return ResourceManager.GetString("SaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save type ?                    |.
        /// </summary>
        internal static string SaveType {
            get {
                return ResourceManager.GetString("SaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Complete.
        /// </summary>
        internal static string SaveTypeAnswer1 {
            get {
                return ResourceManager.GetString("SaveTypeAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Differential.
        /// </summary>
        internal static string SaveTypeAnswer2 {
            get {
                return ResourceManager.GetString("SaveTypeAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Logs.
        /// </summary>
        internal static string ShowLogs {
            get {
                return ResourceManager.GetString("ShowLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show schedule.
        /// </summary>
        internal static string ShowSchedule {
            get {
                return ResourceManager.GetString("ShowSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show state file.
        /// </summary>
        internal static string ShowStateFile {
            get {
                return ResourceManager.GetString("ShowStateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Directory ?            |.
        /// </summary>
        internal static string SourceDirectory {
            get {
                return ResourceManager.GetString("SourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source does not exist or is neither a file nor a directory..
        /// </summary>
        internal static string SourceError {
            get {
                return ResourceManager.GetString("SourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target file ?                  |.
        /// </summary>
        internal static string TargetFile {
            get {
                return ResourceManager.GetString("TargetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string TypeAnswer1 {
            get {
                return ResourceManager.GetString("TypeAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Différential.
        /// </summary>
        internal static string TypeAnswer2 {
            get {
                return ResourceManager.GetString("TypeAnswer2", resourceCulture);
            }
        }
    }
}
