//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesFR_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesFR_FR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Core.Resources.ResourcesFR-FR", typeof(ResourcesFR_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le dossier a bien été copié..
        /// </summary>
        internal static string DirectoryCopied {
            get {
                return ResourceManager.GetString("DirectoryCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certains éléments :.
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appuyez sur ENTRER pour quitter .
        /// </summary>
        internal static string EnterExit {
            get {
                return ResourceManager.GetString("EnterExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres invalides détectés.
        /// </summary>
        internal static string ErrorEmptySave {
            get {
                return ResourceManager.GetString("ErrorEmptySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermeture de EasySave ....
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier a bien été copié..
        /// </summary>
        internal static string FileCopied {
            get {
                return ResourceManager.GetString("FileCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source : .
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choix invalide.
        /// </summary>
        internal static string InvalidChoice {
            get {
                return ResourceManager.GetString("InvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  est en cours d&apos;exécution....
        /// </summary>
        internal static string IsRunning {
            get {
                return ResourceManager.GetString("IsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une Liste :.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-3 =&gt; 1 à 3                                  |.
        /// </summary>
        internal static string ListAnswer1 {
            get {
                return ResourceManager.GetString("ListAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,3 =&gt; 1 et 3                         |.
        /// </summary>
        internal static string ListAnswer2 {
            get {
                return ResourceManager.GetString("ListAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur : Vous avez atteint le nombre maximum de sauvegardes.
        /// </summary>
        internal static string MaxSaveError {
            get {
                return ResourceManager.GetString("MaxSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | 1 - Planifier une sauvegarde....................          |.
        /// </summary>
        internal static string Menu1 {
            get {
                return ResourceManager.GetString("Menu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | 2 - Exécuter une sauvegarde.....................          |.
        /// </summary>
        internal static string Menu2 {
            get {
                return ResourceManager.GetString("Menu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | 3 - Afficher Logs...............................          |.
        /// </summary>
        internal static string Menu3 {
            get {
                return ResourceManager.GetString("Menu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | 4 - Afficher le fichier d&apos;état..................          |.
        /// </summary>
        internal static string Menu4 {
            get {
                return ResourceManager.GetString("Menu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | 5 - Afficher la plannification..................          |.
        /// </summary>
        internal static string Menu5 {
            get {
                return ResourceManager.GetString("Menu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 - Quitter......................................
        /// </summary>
        internal static string Menu6 {
            get {
                return ResourceManager.GetString("Menu6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom :  .
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          1- .
        /// </summary>
        internal static string Number1 {
            get {
                return ResourceManager.GetString("Number1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          2- .
        /// </summary>
        internal static string Number2 {
            get {
                return ResourceManager.GetString("Number2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          3- .
        /// </summary>
        internal static string Number3 {
            get {
                return ResourceManager.GetString("Number3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         4- .
        /// </summary>
        internal static string Number4 {
            get {
                return ResourceManager.GetString("Number4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       5- .
        /// </summary>
        internal static string Number5 {
            get {
                return ResourceManager.GetString("Number5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cible : .
        /// </summary>
        internal static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planifier une sauvegarde.
        /// </summary>
        internal static string PlanSave {
            get {
                return ResourceManager.GetString("PlanSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |                Que voulez-vous exécuter ?                |.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executer une sauvegarde.
        /// </summary>
        internal static string RunSave {
            get {
                return ResourceManager.GetString("RunSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de la sauvegarde ?            |.
        /// </summary>
        internal static string SaveDate {
            get {
                return ResourceManager.GetString("SaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la sauvegarde ?           |.
        /// </summary>
        internal static string SaveName {
            get {
                return ResourceManager.GetString("SaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de Sauvegarde ?            |.
        /// </summary>
        internal static string SaveType {
            get {
                return ResourceManager.GetString("SaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Complète.
        /// </summary>
        internal static string SaveTypeAnswer1 {
            get {
                return ResourceManager.GetString("SaveTypeAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Différentielle.
        /// </summary>
        internal static string SaveTypeAnswer2 {
            get {
                return ResourceManager.GetString("SaveTypeAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher Logs.
        /// </summary>
        internal static string ShowLogs {
            get {
                return ResourceManager.GetString("ShowLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la plannification.
        /// </summary>
        internal static string ShowSchedule {
            get {
                return ResourceManager.GetString("ShowSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le fichier d&apos;état.
        /// </summary>
        internal static string ShowStateFile {
            get {
                return ResourceManager.GetString("ShowStateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répertoire d&apos;entrée ?           |.
        /// </summary>
        internal static string SourceDirectory {
            get {
                return ResourceManager.GetString("SourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La source n&apos;existe pas ou n&apos;est ni un fichier ni un répertoire..
        /// </summary>
        internal static string SourceError {
            get {
                return ResourceManager.GetString("SourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier de sortie ?             |.
        /// </summary>
        internal static string TargetFile {
            get {
                return ResourceManager.GetString("TargetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complète.
        /// </summary>
        internal static string TypeAnswer1 {
            get {
                return ResourceManager.GetString("TypeAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Différentiel.
        /// </summary>
        internal static string TypeAnswer2 {
            get {
                return ResourceManager.GetString("TypeAnswer2", resourceCulture);
            }
        }
    }
}
